name: Changelog Entry Creator

on:
  pull_request:
    types: [opened]
        
jobs:
  create-changelog-entry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        ssh-key: ${{ secrets.ssh_key }}
    - uses: blackjacx/changelog@master
      with:
        changelog-folder-path: 'changelog'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
