name: Move Referenced Issue On PR Merge

on:
  pull_request:
    branches: develop
    types: closed

jobs:
  move-issue:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v3
    - uses: blackjacx/backlog-notifier@add-actions-input
      with:
        repo-references: |
          {
            "data": [
              {"repo_id": "BACKLOG", "repo_name": "backlog"},
              {"repo_id": "GHTEST", "repo_name": "ghtest"}
            ]
          }
        action: move
        new-project-board-column: 'Done'
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
